language: node_js
node_js:
  - "0.11"

before_install:
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.0.2
  - export PATH=$PATH:`pwd`/bin
  - cd -

notifications:
  irc:
    channels:
      - "chat.freenode.net#idleplaythings"
    on_success: always
    on_failure: always
    skip_join: true
